draw_letter_d:
  ros__parameters:
    use_sim_time: true

    letter_height: 0.12
    letter_width: 0.08
    arc_points: 50

    eef_step: 0.003
    jump_threshold: 2.0
    min_fraction: 0.999

    velocity_scale: 0.12
    acceleration_scale: 0.12

    # 0 = lap vo han, >0 = so lan ve
    repeat_count: 0
    repeat_delay: 2.0
    guide_wait_time: 10.0

    ready_joints: [0.0, -1.5708, 1.5708, -1.5708, -1.5708, 0.0]