draw_circle:
  ros__parameters:
    use_sim_time: true

    # Ban kinh 7 cm -> duong kinh 14 cm
    circle_radius: 0.07
    circle_points: 100

    eef_step: 0.003
    jump_threshold: 2.0
    min_fraction: 0.999

    velocity_scale: 0.12
    acceleration_scale: 0.12

    guide_wait_time: 10.0

    # 0 = lap vo han
    repeat_count: 0
    repeat_delay: 2.0

    ready_joints: [0.0, -1.5708, 1.5708, -1.5708, -1.5708, 0.0]